[build]
  command = "rm -f HardwareReport/Main.js && echo 'Skipping build, deploying static files'"
  publish = "."  # Remplace par le dossier où se trouvent tes fichiers statiques (ex. '.', 'dist', 'build').

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200