[build]
  command = "echo 'Skipping build, serving static files'"
  publish = "."  # Le répertoire racine où se trouvent tes fichiers (ex: index.html)

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
