[build]
  # la commande à exécuter – ça va lancer "npm run build" qui est juste un echo
  command   = "npm run build"
  # publier toute la racine du repo
  publish   = "."
  # indique où sont tes lambdas
  functions = "netlify/functions"

# si tu veux toujours servir index.html depuis chaque sous?dossier
[[redirects]]
  from    = "/*"
  to      = "/:splat/index.html"
  status  = 200
