[build]
  publish = "public"  # Ensure this points to the correct folder where your static files are stored.

# Custom command to remove or ignore problematic files
[[plugins]]
  package = "@netlify/plugin-skip-build"

[functions]
  ignore_files = ["Main.js", "some-other-file.js"] # Add any files you want to ignore during deployment